#!/bin/sh
[ -e "$HOME/.vars.env" ] && . "$HOME/.vars.env"
load_comps() {
  [ ! -d "$SHELL_COMPS" ] && return
  command -v lb > /dev/null && LB_COMP="$SHELL_COMPS/lb.sh" && [ ! -s "$LB_COMP" ] && lb completions > "$LB_COMP"
  for FILE in $(find "$SHELL_COMPS" -type f -name "*.sh"); do
    . "$FILE"
  done
}

ssh_agent() {
  envfile="$HOME/.local/state/ssh-agent.env"
  mkdir -p "$(dirname "$envfile")"
  if ! pgrep -u "$USER" '^ssh-agent$' > /dev/null; then
    ssh-agent > "$envfile"
  fi
  export SSH_AUTH_SOCK="$HOME/.local/state/ssh-agent.socket"
  if [ ! -f "$SSH_AUTH_SOCK" ]; then
    . "$envfile" > /dev/null
  fi
  ssh-add "$HOME/.ssh/"*.privkey >/dev/null 2>&1
}

shell_ready() {
  unset -f load_comps ssh_agent shell_ready post_setup
}

post_setup() {
  [ -e "$HOME/.$(basename $SHELL).is_setup" ] && . "$HOME/.$(basename $SHELL).is_setup"
}

export SHELL_COMPS="$HOME/.local/share/completions"
export SECRET_ROOT="$HOME/.ttypty/secrets"
[ -e "$HOME/.config/ttypty/editor" ] && export EDITOR=$(cat "$HOME/.config/ttypty/editor")
if [ -z "$EDITOR" ]; then
  export EDITOR=vim
  command -v nvim > /dev/null && export EDITOR=nvim
fi
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
[ "$EDITOR" != vim ] && alias vim="$EDITOR"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

if command -v go >/dev/null; then
  [ -n "$XDG_CACHE_HOME" ] && export GOPATH="$XDG_CACHE_HOME/go"
  [ -d "$GOPATH" ] && export PATH="$GOPATH/bin:$PATH"
fi

alias vi="\$EDITOR"
alias less="less -R"
if command -v bat > /dev/null; then
  alias cat=bat
  export BAT_OPTS="-pp --theme 'Monokai Extended'"
  export LESSOPEN="| bat %s --color=always"
  export LESS="-R"
fi
command -v rg > /dev/null && alias grep="rg"
if command -v delta > /dev/null; then
  export GIT_PAGER=delta
  export DELTA_PAGER="less -R -c -X"
fi
command -v git-uncommitted > /dev/null && export GIT_UNCOMMITTED="$(git-uncommitted paths)"
[ -e "$HOME/.$(basename $SHELL).vars" ] && . "$HOME/.$(basename $SHELL).vars"
