#!/bin/sh -e
VERSION=0.10.0
FILE="$PKGS_WORKDIR/$VERSION.shellcheck.tar.xz"
[ "$OS" = "darwin" ] && HASH="bbd2f14"
[ "$OS" = "linux" ] && HASH="324a7e8"

download-and-check \
  -u "https://github.com/koalaman/shellcheck/releases/download/v$VERSION/shellcheck-v$VERSION.$OS.$PKGS_ARCH.tar.xz" \
  -f "$FILE" \
  -h "$HASH"

TO="$PKGS_ROOT/shellcheck/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-component=1 -C "$TO"
echo "export PATH=\"$TO/:\$PATH\"" > "$ENV"
