#!/bin/bash
_install() {
  case "$(basename "$SHELL")" in
    "zsh")
      echo ".zshrc"
      ;;
  esac

  echo ".config/vim/"
  echo ".config/git/"
  echo ".ssh/"
  case $(uname) in
    "Darwin")
      echo ".config/pkgversions/"
      echo ".config/kitty/"
      echo ".config/vfu/"
      ;;
  esac
}

DRYRUN=0
if [ -n "$1" ]; then
  case "$1" in
    "--dry-run")
      DRYRUN=1
      ;;
    *)
      echo "unknown command: $1"
      exit 1
      ;;
  esac
fi

DIR=""
SET=""
FILE=""
for SET in $(_install | sort -u); do
  for FILE in $(find "$SET" -type f); do
    [ "$DRYRUN" -eq 1 ] && echo "$FILE" | sed "s#HOME/##g"
    DIR=$(dirname "$FILE")
    [ "$DIR" != "." ] && mkdir -p "$HOME/$DIR"
    CMD="ln -sf"
    $CMD "$PWD/$FILE" "$HOME/$FILE"
  done
done

unset SET DIR FILE DRYRUN
