#!/bin/sh
if [ -d "/opt/homebrew" ]; then
  BREW_ENV="$HOME/.local/share/brewenv"
  [ -e "$BREW_ENV" ] && find "$BREW_ENV" -type f -mtime +1 -delete
  [ ! -e "$BREW_ENV" ] && /opt/homebrew/bin/brew shellenv > "$BREW_ENV"
  . "$BREW_ENV"
  unset BREW_ENV
  for NAME in "make" "curl" "gnu-sed" "findutils" "coreutils"; do
    for DIR in "/opt/homebrew/opt/$NAME/libexec/gnubin" "/opt/homebrew/opt/$NAME/bin"; do
      [ -d "$DIR" ] && export PATH="$DIR:$PATH" && break
    done
  done
  DIR="$HOMEBREW_PREFIX/share/zsh-completion"
  [ -d "$DIR" ] && export FPATH="$DIR:$FPATH"
  unset DIR NAME
  export HOMEBREW_NO_AUTO_UPDATE=1
fi
