#!/bin/sh
COMPS="$HOME/.local/share/completions"
mkdir -p "$COMPS"
COMP_SHELL="$(basename "$SHELL")"

_gencomp() {
  NAME="$1"
  VERS="$(echo $2 | sha256sum | cut -c 1-7)"
  FILE="$COMPS/$NAME.$VERS.sh"
  if [ ! -e "$FILE" ]; then
    find "$COMPS" -type f -name "$NAME.*" -delete
    if ! "$1" $3 > "$FILE"; then
      rm -f "$FILE"
    fi
  fi
  [ "$COMP_SHELL" = "zsh" ] && ln -sf "$FILE" "$COMPS/_$NAME"
}


if command -v wac > /dev/null; then
  _gencomp \
    wac \
    "$(wac version)" \
    "completions"
fi

if command -v lb > /dev/null; then
  _gencomp \
    lb \
    "$(lb version)" \
    "completions"
fi

if command -v pkgversions > /dev/null; then
  _gencomp \
    pkgversions \
    "$(pkgversions -v)" \
    "-c"
fi

if command -v container > /dev/null; then
  _gencomp \
    container \
    "$(container --version)" \
    "--generate-completion-script"
fi

if command -v devcontainer > /dev/null; then
  _gencomp \
    devcontainer \
    "$(devcontainer version)" \
    "completions"
fi

case "$COMP_SHELL" in
  "zsh")
    export FPATH="$COMPS:$FPATH"
    autoload -Uz compinit && compinit
    ;;
  "bash")
    for FILE in $(find "$COMPS" -type f); do
      source "$FILE"
    done
    ;;
esac
