#!/bin/sh
export SHELL_COMPS="$HOME/.local/share/completions"
mkdir -p "$SHELL_COMPS"

_gencomp() {
  NAME="$1"
  VERS="$(echo $2 | sha256sum | cut -c 1-7)"
  FILE="$SHELL_COMPS/$NAME.$VERS.sh"
  if [ ! -e "$FILE" ]; then
    find "$SHELL_COMPS" -type f -name "$NAME.*" -delete
    if ! "$1" $3  | sed 's/^_container$/compdef _container container/g' > "$FILE"; then
      rm -f "$FILE"
    fi
  fi
}

if command -v lb > /dev/null; then
  _gencomp \
    lb \
    "$(lb version)" \
    "completions"
fi

if command -v container > /dev/null; then
  _gencomp \
    container \
    "$(container --version)" \
    "--generate-completion-script"
fi

if command -v devcontainer > /dev/null; then
  _gencomp \
    devcontainer \
    "$(devcontainer version)" \
    "completions"
fi
