#!/bin/sh -e
dev_id() {
  IDENTIFIER="${TOOLS_IDENTIFIER:-}"
  [ -n "$IDENTIFIER" ] && echo "$IDENTIFIER" && return
  IDENTIFIER="${CONTAINER_IDENTIFIER:-}"
  echo "$IDENTIFIER"
}

go_tools() {
  echo "mvdan.cc/gofumpt"
  echo "golang.org/x/tools/gopls"
  echo "honnef.co/go/tools/cmd/staticcheck"
  echo "github.com/enckse/lockbox/cmd/lb"
  echo "github.com/mgechev/revive"
}

npm_tools() {
  echo "typescript"
  echo "typescript-language-server"
}

rust_tools() {
  echo "rust-analyzer"
}
