#!/bin/sh
go_version \
  "https://git.sr.ht/~enckse/lockbox" \
  "git.sr.ht/~enckse/lockbox/cmd/lb" \
  "v1.9.0"
go_version \
  "https://github.com/dominikh/go-tools" \
  "honnef.co/go/tools/cmd/staticcheck" \
  "v0.6.1"
go_version \
  "https://github.com/mgechev/revive" \
  "github.com/mgechev/revive" \
  "v1.10.0"
go_version \
  "https://github.com/golang/tools" \
  "golang.org/x/tools/gopls" \
  "v0.19.1"
go_version \
  "https://github.com/mvdan/gofumpt" \
  "mvdan.cc/gofumpt" \
  "v0.8.0"
go_version \
  "https://github.com/theimpostor/osc" \
  "github.com/theimpostor/osc" \
  "v0.4.8"
editor_plugin \
  "https://github.com/vim-airline/vim-airline"
editor_plugin \
  "https://github.com/prabirshrestha/asyncomplete-buffer.vim"
editor_plugin \
  "https://github.com/prabirshrestha/asyncomplete-lsp.vim"
editor_plugin \
  "https://github.com/prabirshrestha/asyncomplete.vim"
editor_plugin \
  "https://github.com/prabirshrestha/vim-lsp"
editor_plugin \
  "https://github.com/bfrg/vim-qf-diagnostics"
editor_plugin \
  "https://github.com/itspriddle/vim-shellcheck"
check_version \
  "https://github.com/apple/container"
check_version \
  "https://github.com/kovidgoyal/kitty"
check_version \
  "https://github.com/rxhanson/Rectangle"
check_version \
  "https://gitlab.alpinelinux.org/alpine/aports.git/"
check_version \
  "https://github.com/restic/restic"
check_version \
  "https://github.com/swiftbar/SwiftBar"
