#!/bin/sh
check_version \
  "https://github.com/apple/container"
check_version \
  "https://github.com/kovidgoyal/kitty"
check_version \
  "https://github.com/rxhanson/Rectangle"
check_version \
  "https://gitlab.alpinelinux.org/alpine/aports.git/"
check_version \
  "https://github.com/restic/restic"
check_version \
  "https://github.com/swiftbar/SwiftBar"
