#!/bin/sh
GOPLS_VERS="v0.19.1"
go_version \
  "https://git.sr.ht/~enckse/lockbox" \
  "git.sr.ht/~enckse/lockbox/cmd/lb" \
  "v1.7.0"
go_version \
  "https://git.sr.ht/~enckse/git-tools" \
  "git.sr.ht/~enckse/git-tools/cmd/..." \
  "v0.5.0"
go_version \
  "https://github.com/dominikh/go-tools" \
  "honnef.co/go/tools/cmd/staticcheck" \
  "v0.6.1"
go_version \
  "https://github.com/mgechev/revive" \
  "github.com/mgechev/revive" \
  "v1.10.0"
go_version \
  "https://github.com/golang/tools" \
  "golang.org/x/tools/gopls" \
  "$GOPLS_VERS"
go_version \
  "https://github.com/mvdan/gofumpt" \
  "mvdan.cc/gofumpt" \
  "v0.8.0"
go_install \
  "golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize" \
  "$GOPLS_VERS"
go_install \
  "golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" \
  "v0.34.0"
case "$DOTFILES_EDITOR" in
  "vim")
    editor_plugin \
      "https://github.com/vim-airline/vim-airline"
	editor_plugin \
      "https://github.com/prabirshrestha/asyncomplete-buffer.vim"
	editor_plugin \
      "https://github.com/prabirshrestha/asyncomplete-lsp.vim"
	editor_plugin \
      "https://github.com/prabirshrestha/asyncomplete.vim"
	editor_plugin \
      "https://github.com/prabirshrestha/vim-lsp"
	editor_plugin \
      "https://github.com/bfrg/vim-qf-diagnostics"
	editor_plugin \
      "https://github.com/itspriddle/vim-shellcheck"
    ;;
esac
check_version \
  "https://github.com/apple/container"
check_version \
  "https://github.com/kovidgoyal/kitty"
check_version \
  "https://github.com/rxhanson/Rectangle"
check_version \
  "https://gitlab.alpinelinux.org/alpine/aports"
check_version \
  "https://github.com/restic/restic"
