#!/bin/sh
motdheader() {
  echo "[$1]"
  echo "==="
}

motd() {
  data=$($@)
  if [ -z "$data" ]; then
    return
  fi
  motdheader "$1"
  echo "$data"
  echo
}

sshagent() {
  envfile="$HOME/.local/state/ssh-agent.env"
  mkdir -p "$(dirname "$envfile")"
  if ! pgrep -u "$USER" '^ssh-agent$' > /dev/null; then
    ssh-agent > "$envfile"
  fi
  export SSH_AUTH_SOCK="$HOME/.local/state/ssh-agent.socket"
  if [ ! -f "$SSH_AUTH_SOCK" ]; then
    . "$envfile" > /dev/null
  fi
  ssh-add "$HOME/.ssh/"*.privkey >/dev/null 2>&1
}

uncommitted() {
  if command -v git-uncommitted > /dev/null; then
    motd git uncommitted
  fi
}

cleancaches() {
  for DIR in ".cache/staticcheck" \
             ".cache/gopls" \
             ".cache/go-build" \
             ".cache/vim"; do
    DIR="$HOME/$DIR"
    [ -d "$DIR" ] && find "$DIR" -type f -mmin +120 -delete
  done
}

shellready() {
  unset -f uncommitted cleancaches sshagent motd motdheader
}


export PKGV_STORE="$HOME/.pkgv"
[ -e "$PKGV_STORE/env" ] && source "$PKGV_STORE/env"

export SECRET_ROOT="$HOME/.ttypty/secrets"
export EDITOR=vim
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
export GOPATH="$HOME/.cache/go"
[ -d "$GOPATH" ] && export PATH="$GOPATH/bin:$PATH"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"

alias vi="\$EDITOR"
alias less="less -R"
if command -v bat > /dev/null; then
  alias cat=bat
  export BAT_OPTS="-pp --theme 'Monokai Extended'"
fi
command -v rg > /dev/null && alias grep="rg"
if command -v delta > /dev/null; then
  export GIT_PAGER=delta
  export DELTA_PAGER="less -R -c -X"
fi

