#!/bin/sh
load_comps() {
  [ ! -e "$HOME/.config/dotfiles/completions" ] && return
  . "$HOME/.config/dotfiles/completions"
  for FILE in $(find "$SHELL_COMPS" -type f -name "*.sh"); do
    . "$FILE"
  done
}

ssh_agent() {
  envfile="$HOME/.local/state/ssh-agent.env"
  mkdir -p "$(dirname "$envfile")"
  if ! pgrep -u "$USER" '^ssh-agent$' > /dev/null; then
    ssh-agent > "$envfile"
  fi
  export SSH_AUTH_SOCK="$HOME/.local/state/ssh-agent.socket"
  if [ ! -f "$SSH_AUTH_SOCK" ]; then
    . "$envfile" > /dev/null
  fi
  ssh-add "$HOME/.ssh/"*.privkey >/dev/null 2>&1
}

container_setup() {
  command -v setup-devcontainer > /dev/null && setup-devcontainer
}

shell_ready() {
  unset -f load_comps ssh_agent container_setup shell_ready
}

export SHELL_COMPS="$HOME/.local/share/completions"
[ -e "$PKGV_STORE/env" ] && source "$PKGV_STORE/env"

export SECRET_ROOT="$HOME/.ttypty/secrets"
export EDITOR=vim
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"
command -v go > /dev/null && export GOPATH="$HOME/.cache/go"
[ -d "$GOPATH" ] && export PATH="$GOPATH/bin:$PATH"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"
[ "$EDITOR" != vim ] && alias vim="$EDITOR"

alias vi="\$EDITOR"
alias less="less -R"
if command -v bat > /dev/null; then
  alias cat=bat
  export BAT_OPTS="-pp --theme 'Monokai Extended'"
fi
command -v rg > /dev/null && alias grep="rg"
if command -v delta > /dev/null; then
  export GIT_PAGER=delta
  export DELTA_PAGER="less -R -c -X"
fi
