#!/usr/bin/env zsh
if command -v wac > /dev/null; then
  _motd wac motd
  wac manage
fi

bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line

vim() {
  echo "no vim"
}
git() {
  echo "no git"
}

autoload -Uz compinit && compinit
for file in $(find "$LOCAL_FS" -type f -name "env.sh"); do
  . "$file"
done

autoload -U promptinit && promptinit
precmd() {
  GIT_UNCOMMIT=""
  if command -v git-uncommitted >/dev/null; then
      GIT_UNCOMMIT=$(NO_COLOR=1 git uncommitted pwd 2>/dev/null)
      COLORING="%{$(tput setaf 1)%}"
      if [ "$GIT_UNCOMMIT" = "(clean)" ]; then
        COLORING="%{$(tput setaf 2)%}"
      fi
      GIT_UNCOMMIT="$COLORING$GIT_UNCOMMIT"
  fi
  PS1="$GIT_UNCOMMIT%{$(tput setaf 226)%}%n%{$(tput setaf 15)%}@%{$(tput setaf 200)%}%m %{$(tput setaf 45)%}%1~ %{$(tput sgr0)%}$ "
}
