#!/bin/sh -e
[ ! -e 'go.mod' ] && echo 'cowardly failing to run go lint commands' && exit 1
go vet ./...
revive  ./...
fieldalignment  ./...
modernize -test ./...
staticcheck -checks all -debug.run-quickfix-analyzers ./...
gofumpt -d -extra $(find . -type f -name "*.go" | tr "\n" " ")
