#!/bin/sh -e
SOURCES=""
WORKDIR=""
ARCH=""
OS=""
OUT=""
while getopts "s:w:a:b:p:" opt ; do
  case $opt in
    s) SOURCES="$OPTARG";;
    w) WORKDIR="$OPTARG";;
    b) OUT="$OPTARG";;
    a) ARCH="$OPTARG";;
    p) OS="$OPTARG";;
    *)
      echo "unknown arg $opt"
      exit 1
      ;;
  esac
done

[ -z "$OUT" ] && echo "no output dir set" && exit 1
[ -z "$WORKDIR" ] && echo "no workdir set" && exit 1
[ -z "$SOURCES" ] && echo "sources not set" && exit 1
[ -z "$ARCH" ] && echo "arch not set" && exit 1
[ -z "$OS" ] && echo "os (platform) not set" && exit 1
[ ! -d "$SOURCES" ] && echo "no $SOURCES dir found" && exit 1

mkdir -p "$OUT" "$WORKDIR"
export PKGS_WORKDIR="$WORKDIR"
export PKGS_ROOT="$OUT"

USE_SHELL=$(basename "$SHELL")
[ "$OS" = "darwin" ] && OS_ALT="macos"
export OS USE_SHELL OS_ALT

export PKGS_LIST="$OUT/pkglist"
rm -f "$PKGS_LIST"

export PKGS_ARCH="$ARCH"
[ "$PKGS_ARCH" = "aarch64" ] && export PKGS_ALTARCH=arm64

case "$OS" in
  "darwin")
    OS_DOUBLE="apple-darwin" && export OS_DOUBLE
    ;;
  "linux")
    export PKGS_LIBC=musl
    OS_DOUBLE="unknown-linux"
    OS_TRIPLE="$OS_DOUBLE-$PKGS_LIBC"
    export OS_DOUBLE OS_TRIPLE
    ;; 
esac

OS_IDENTIFIER="$OS_DOUBLE"
[ -n "$OS_TRIPLE" ] && OS_IDENTIFIER="$OS_TRIPLE"
export OS_IDENTIFIER

for SRC in "$SOURCES/"*.sh; do
  echo "processing: $SRC"
  [ ! -x "$SRC" ] && echo "$SRC is not executable" && exit 1
  "$SRC"
done

sort -u -o "$PKGS_LIST" "$PKGS_LIST"

case "$OS" in
  "linux")
    {
      cat << 'EOF'
version=$(grep "^VERSION_ID=" "/etc/os-release" | cut -d "=" -f 2-)
major=$(echo "$version" | cut -d "." -f 1)
minor=$(echo "$version" | cut -d "." -f 2)
check_version "alpine-release" "https://gitlab.alpinelinux.org/alpine/aports/-/tags?format=atom"
check_version "alpine-kernel" "https://gitlab.alpinelinux.org/alpine/aports/-/commits/$major.$minor-stable/main/linux-lts/APKBUILD?format=atom"
EOF
      cat "$PKGS_LIST"
    } > "$PKGS_LIST.tmp"
    mv "$PKGS_LIST.tmp" "$PKGS_LIST"
    ;;
esac
