#!/bin/sh -e
CACHE="$HOME/Library/com.ttypty/scache"
mkdir -p "$CACHE"
find "$CACHE" -type f -mtime +30 -delete
CACHE="$CACHE/$(date +%Y-%m-%d)"
[ ! -e "$CACHE" ] && git -C "$SECRET_ROOT" pull >/dev/null 2>&1 && touch "$CACHE"
