filetype plugin on
filetype plugin indent on
syntax on

function CleanVimDir(path, threshold)
  call system("test -d " . a:path . " && find " . a:path . " -type f " . a:threshold . " -delete")
endfunction

function SetupVimDir(path)
    if ! isdirectory(expand(a:path))
        call mkdir(expand(a:path), 'p', 0700)
    endif
endfunction

set viminfo+=n$HOME/.cache/vim/viminfo
let &g:directory=$HOME . '/.cache/vim'
call CleanVimDir(&g:directory, "-mtime +1")

let &g:undodir=&g:directory . '/undo/'
let &g:backupdir=&g:directory . '/backup/'
let &g:directory=&g:directory . '/swap/'
call SetupVimDir(&g:directory)
call SetupVimDir(&g:undodir)
call SetupVimDir(&g:backupdir)
call CleanVimDir(&g:undodir, "-mmin +60")

let loaded_netrwPlugin = 1
