version: 2
root-markers:
  - .git/

tools:
  bash-shellcheck: &bash-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  bash-bufcomp: &bash-bufcomp
      completion-command: 'bufcomp'

languages:
  bash:
    - <<: *bash-bufcomp
    - <<: *bash-shellcheck
