#!/bin/sh -e

TO="$PKGS_ROOT/vim-plugins"
PLUGS="vim-airline/vim-airline dense-analysis/ale"

DEST=""
for PLUG in $PLUGS; do
  DIR="$PKGS_WORKDIR/$(basename "$PLUG").git"
  [ ! -d "$DIR" ] && git clone --quiet "https://github.com/$PLUG" "$DIR"
  git -C "$DIR" pull --quiet
  HASH=$(git -C "$DIR" log -n 1 --pretty=format:"%h")
  DEST="$DEST$HASH"
done

TO="$PKGS_ROOT/vim-plugins/$DEST"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
for PLUG in $PLUGS; do
  NAME="$(basename "$PLUG")"
  DIR="$PKGS_WORKDIR/$NAME.git"
  TARGET="$TO/$NAME"
  [ -d "$TARGET" ] && continue
  cp -r "$DIR" "$TARGET"
  rm -rf "$TARGET/.git"
done

VIM_PACK="$HOME/.config/vim/pack/plugins/start"
mkdir -p "$(dirname "$VIM_PACK")"
{
  echo "_vimlink() {"
  echo "  [ -e \"$VIM_PACK\" ] && [ \$(readlink \"$VIM_PACK\") = \"$TO\" ] && return"
  echo "  rm -f \"$VIM_PACK\""
  echo "  ln -sf \"$TO\" \"$VIM_PACK\""
  echo "}"
  echo "_vimlink"
} > "$ENV"
