#!/bin/sh -e
VERSION="v9.1.1414"
FILE="$PKGS_WORKDIR/$VERSION.vim.tar.gz"
HASH="48db5a9"

download-and-check \
  -u "https://github.com/vim/vim/archive/refs/tags/$VERSION.tar.gz" \
  -f "$FILE" \
  -h "$HASH" \
  -s '00$'

TO="$PKGS_ROOT/vim/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
(cd "$TO" && ./configure \
                    --enable-multibyte \
                    --with-tlib=ncurses \
                    --enable-terminal \
                    --disable-gui \
                    --without-x)
(cd "$TO" && make)
{
  echo "export PATH=\"$TO/src/:\$PATH\"" 
  echo "export VIM=\"$TO\"
} > "$ENV"
