#!/bin/sh -e
VERSION=1.24.3
[ "$OS" = "darwin" ] && HASH="64a3fa2"
[ "$OS" = "linux" ] && HASH="8df5750"
FILE="$PKGS_WORKDIR/$VERSION.go.tar.gz"

download-and-check \
  -u "https://go.dev/dl/go$VERSION.$OS-$PKGS_ALTARCH.tar.gz" \
  -f "$FILE" \
  -h "$HASH" \
  -p "https://github.com/golang/go"

TO="$PKGS_ROOT/go/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
echo "export PATH=\"$TO/bin/:\$PATH\"" > "$ENV"
