#!/bin/sh -e
GOTOOLS="
git.sr.ht/~enckse/git-tools/cmd/...
git.sr.ht/~enckse/lockbox/cmd/lb
github.com/mgechev/revive 
golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize
honnef.co/go/tools/cmd/staticcheck
mvdan.cc/gofumpt
golang.org/x/tools/gopls
github.com/restic/restic/cmd/restic
"

command -v go > /dev/null

GOMODS="$PKGS_BIN/go-mod-updates"
{
  echo "#!/bin/sh -e"
  echo "go get -u ./..."
  echo "go mod tidy"
} > "$GOMODS"
chmod 755 "$GOMODS"

_pkgv() {
  echo "check_version 'https://$1'" >> "$PKGS_LIST"
}

GOLINT="$PKGS_BIN/go-lint"
_golint() {
  NAMED="$(basename "$1")"
  ARGS="$2"
  FILES="$3"
  [ -z "$FILES" ] && FILES="./..."
  echo "$NAMED $ARGS $FILES" >> "$GOLINT"
}

{
  echo "#!/bin/sh -e"
  echo "go vet ./..."
} > "$GOLINT"
for f in $GOTOOLS; do
  versioning=""
  case "$f" in
    git.sr.ht/* | github.com/*)
      _pkgv "$(echo "$f" | cut -d "/" -f 1,2,3)"
      case "$f" in
        *enckse/git-tools*)
          versioning="v0.3.0"
          ;;
        *enckse/lockbox*)
          versioning="v1.4.5"
          ;;
        *mgechev/revive*)
          versioning="v1.9.0"
          _golint "$f"
          ;;
        *restic/restic*)
          versioning="v0.18.0"
          ;;
      esac
      ;; 
    */fieldalignment)
      versioning=latest
      _golint "$f"
      ;;
    */cmd/staticcheck)
      _pkgv "github.com/dominikh/go-tools"
      versioning="v0.6.1"
      _golint "$f" "-checks all -debug.run-quickfix-analyzers"
      ;;
    */modernize | */tools/gopls)
      _pkgv "github.com/golang/tools"
      versioning="v0.18.1"
      case "$f" in
        */modernize)
          _golint "$f" "-test"
          ;;
      esac
      ;;
    */gofumpt)
      _pkgv "github.com/mvdan/gofumpt"
      _golint "$f" "-d -extra" '$(find . -type f -name "*.go" | tr "\\n" " ")'
      versioning="v0.8.0"
      ;;
    *)
      echo "unable to package version: $f" >&2
      exit 1
      ;;
  esac
  [ -z "$versioning" ] && echo "no version set: $f" && exit 1
  (cd "$PKGS_BIN" && GOBIN="$PWD" ./go install "$f@$versioning")
done
(cd "$PKGS_BIN" && SHELL="$USE_SHELL" ./lb completions > "$PKGS_COMP/lb")
chmod 755 "$GOLINT"
