#!/bin/sh -e
VERSION=0.25.0
FILE="$PKGS_WORKDIR/$VERSION.bat.tar.gz"
[ "$OS" = "darwin" ] && HASH="b3ed5a7"
[ "$OS" = "linux" ] && HASH="ee0f12c"

download-and-check \
  -u "https://github.com/sharkdp/bat/releases/download/v$VERSION/bat-v$VERSION-$PKGS_ARCH-$OS_IDENTIFIER.tar.gz" \
  -f "$FILE" \
  -h "$HASH"

TO="$PKGS_ROOT/bat/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
echo "export PATH=\"$TO/:\$PATH\"" > "$ENV"
