#!/bin/sh -e
VERSION=1.40.0
[ "$OS" = "darwin" ] && HASH="0fb2401"
[ "$OS" = "linux" ] && HASH="d065d0d"
FILE="$PKGS_WORKDIR/$VERSION.just.tar.gz"

download-and-check \
  -u "https://github.com/casey/just/releases/download/$VERSION/just-$VERSION-$PKGS_ARCH-$OS_IDENTIFIER.tar.gz" \
  -f "$FILE" \
  -h "$HASH"

TO="$PKGS_ROOT/just/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" -C "$TO"
{
  echo "export PATH=\"$TO/:\$PATH\""
  echo "export USRBIN_COMP=\"$TO/completions/just.$USE_SHELL:\$USRBIN_COMP\""
} > "$ENV"
