#!/bin/sh -e
VERSION=14.1.1
FILE="$PKGS_WORKDIR/$VERSION.rg.tar.gz"
[ "$OS" = "darwin" ] && HASH="24ad767"
[ "$OS" = "linux" ] && HASH="c827481"

download-and-check \
  -u "https://github.com/BurntSushi/ripgrep/releases/download/$VERSION/ripgrep-$VERSION-$PKGS_ARCH-$OS_IDENTIFIER.tar.gz" \
  -f "$FILE" \
  -h "$HASH"

TO="$PKGS_ROOT/rg/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
echo "export PATH=\"$TO/:\$PATH\"" > "$ENV"
