#!/bin/sh -e
VERSION="4.9"
FILE="$PKGS_WORKDIR/$VERSION.sed.tar.gz"
HASH="6e226b7"

download-and-check \
  -u "https://ftp.gnu.org/pub/gnu/sed/sed-$VERSION.tar.xz" \
  -f "$FILE" \
  -h "$HASH" \
  -p "https://github.com/mirror/sed"

TO="$PKGS_ROOT/sed/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
(cd "$TO" && ./configure \
                    --disable-i18n \
                    --disable-nls)
(cd "$TO" && make)
echo "export PATH=\"$TO/sed:\$PATH\"" > "$ENV"
