#!/bin/bash
VERSION="$(date +%Y%m%dT%H%M%S).$(git describe --always --dirty --abbrev=7)"
libexec() {
  echo "generating: $1"
  BIN="libexec/bin/$1.sh"
  [ ! -e "$BIN" ] && echo "$1 is not valid" && exit 1
  TO="$HOME/.local/bin/$1"
  cat libexec/lib/header.sh | sed "s/\"development\"/\"$VERSION\"/g;s/SCRIPT_NAME/$1/g" > "$TO"
  cat "$BIN" | base64 >> "$TO"
  chmod 755 "$TO"
}

libexec "$1"
