#!/bin/bash
VERSION="$(date +%Y%m%dT%H%M%S).$(git describe --always --dirty --abbrev=7)"
libexec() {
  echo "generating: $1"
  TO="$HOME/.local/bin/$1"
  cat libexec/lib/header.sh | sed "s/\"development\"/\"$VERSION\"/g;s/SCRIPT_NAME/$1/g" > "$TO"
  cat "libexec/bin/$1.sh" | base64 >> "$TO"
  chmod 755 "$TO"
}


ls "$HOME/.config/ttypty" | grep -q "devtools" && libexec "devtools"
case "$(uname)" in
  "Darwin")
    libexec "is-screen-locked"
    libexec "devcontainer"
    ;;
esac
libexec "git-uncommitted"
command -v go > /dev/null && libexec "go-lint" && libexec "go-mod-updates"
