#!/bin/sh -e
! command -v go >/dev/null && echo "no go package found" && exit 1
! command -v just >/dev/null && echo "no just package found" && exit 1

REPO="private:wac"
HASH=$(git ls-remote "$REPO" | grep "HEAD" | cut -c 1-7)
TO="$PKGS_ROOT/wac/$HASH"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

git clone --quiet private:wac "$TO"
(cd "$TO" && just)
echo "export PATH=\"$TO/target/:\$PATH\"" > "$ENV"
