FROM scratch

ARG USER_NAME

ADD minirootfs.tar.gz /
RUN apk update && apk upgrade && apk add --no-cache \
    abuild \
    age \
    alpine-baselayout \
    alpine-conf \
    alpine-keys \
    alpine-release \
    apk-tools \
    bash \
    bash-completion \
    bat \
    busybox \
    curl \
    delta \
    doas \
    docs \
    git \
    go \
    kitty-terminfo \
    libc-utils \
    make \
    openssh \
    openssl \
    ripgrep \
    shellcheck \
    tzdata \
    unzip \
    vim

RUN echo "permit nopass :wheel" > /etc/doas.d/doas.conf
RUN printf "" > /etc/motd
RUN adduser -D $USER_NAME -H -s /bin/bash && addgroup $USER_NAME wheel
RUN passwd -u $USER_NAME
RUN ln -sf /usr/share/zoneinfo/US/Eastern /etc/localtime
RUN ssh-keygen -A

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
