theme = "ttypty"

[editor]
true-color = true
middle-click-paste = false
auto-pairs = false
bufferline = "always"
continue-comments = false
indent-heuristic = "simple"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

[keys.normal]
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"
C-w = "wclose"
C-e = "diagnostics_picker"
