#!/bin/sh -e
VERSION=5.4.7
[ "$OS" = "darwin" ] && HASH="9fbf5e2"
FILE="$PKGS_WORKDIR/$VERSION.lua.tar.gz"

download-and-check \
  -u "https://www.lua.org/ftp/lua-$VERSION.tar.gz" \
  -f "$FILE" \
  -h "$HASH" \
  -p "https://github.com/lua/lua"

TO="$PKGS_ROOT/lua/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" --strip-components=1 -C "$TO"
(cd "$TO" && make)
echo "export PATH=\"$TO/src/:\$PATH\"" > "$ENV"
