#!/bin/sh -e
VERSION=3.14.0
FILE="$PKGS_WORKDIR/$VERSION.luals.tar.gz"
[ "$OS" = "darwin" ] && HASH="85d67a1"

download-and-check \
  -u "https://github.com/LuaLS/lua-language-server/releases/download/$VERSION/lua-language-server-$VERSION-$OS-$PKGS_ALTARCH.tar.gz" \
  -f "$FILE" \
  -h "$HASH"

TO="$PKGS_ROOT/luals/$VERSION"
ENV="$TO/.usrbin"
[ -e "$ENV" ] && exit 0

mkdir -p "$TO"
tar xf "$FILE" -C "$TO"
TARGET="$TO/lua-language-server"
{
  cat << EOF
#!/usr/bin/env sh
TMPPATH="/tmp/lua-language-server-\$(id -u)"
mkdir -p "\$TMPPATH"
INSTANCEPATH=\$(mktemp -d "\$TMPPATH/instance.XXXX")
DEFAULT_LOGPATH="\$INSTANCEPATH/log"
DEFAULT_METAPATH="\$INSTANCEPATH/meta"
LUALS="$TO"

exec \$LUALS/bin/lua-language-server \$LUALS/main.lua \
  --logpath="\$DEFAULT_LOGPATH" --metapath="\$DEFAULT_METAPATH" \
  "\$@"
EOF
} > "$TARGET"
chmod 755 "$TARGET"
echo "export PATH=\"$TO/:\$PATH\"" > "$ENV"
